language: bash
sudo: required
services:
  - docker

before_install:
  - docker pull f5devcentral/containthedocs

script:
  - set -e
  - echo "Test travis deploy."
  - export CTLR_VERSION=$(echo $TRAVIS_BRANCH | sed s/-stable//g)
  - echo "pre CTLR_VERSION=$CTLR_VERSION"

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH == *"-stable"
    script:
      - echo "CTLR_VERSION=$CTLR_VERSION" && ./build-tools/deploy-docs.sh publish-product-docs-to-prod connectors/k8s-bigip-ctlr v$CTLR_VERSION

notifications:
  slack:
    rooms:
      # k8s channel
      - secure: DviXu1iLQaBbF3ya4PLvy/ln6OLTmhCOM3EJBsQpzCWG/YtdONKgOrSNTOqOu1iq3AcUehE2svSgTtg+9qvG+S5iiHwZ0QfJOvTWMr0CogNhb8S8/fVd66UP4oewdJOtyOTNj1F8AQld+8lJR39ZOgkeBKmTQduxv+rt3iJVHuBx9MLbiOTOYVlFQ4mQ+xkAMUPp/fuosjYCyeDYaWrQv6sWISnHShWV8cceCqyeSs+h3I8KOdNmsONkD6z1goqE5UbtZ5rUPLGU70FEoyG1lUCaLNq7f0oDpZGEYPPl9WhDUA1HVEiaArl0w7AneDDz0U5S2V2mwAWG+KYNyMtb5YYkzI2MccqiIPJiux+nUnpXy0cbwrRO1gg5L656dRshM78vp6MHVKDWo8cG+Xz4r6VsEbna3wA0fuIm1XrI/idTH4exGsf5NdoRjITCsNw6tdwaql+RdfMuzvHEd3GWb5oU+nuSf9HTsl4RD5kkNUBquQln/P0motyNmqTP2kCazO/AphV08k7cKxEWdfdR62ETs289spYWa7szGXv2sm/u6r2DakBNLWX6lQbDYRtWBVWclCrH5i1S7yANOnzzgiX4QCQ8Dtg++VvSDrPpH/Q0lYgyw0InPOJIeL1QiUmvVLeCFZnVANQbnn8bLWOJGAl82t2tvRLOT0OOUw+gic0=
    on_success: change
    on_failure: always
    on_pull_requests: false
